disabled_rules:
  - file_length
  - force_cast
  - force_try
  #- function_body_length
  - todo
  #- type_body_length
  - line_length

variable_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0

excluded:
  - Carthage
  - Pods


file_length:
  warning: 600
  error: 1200

cyclomatic_complexity:
  warning: 20
  error: 40

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly